Console.WriteLine("Please Enter value for Math Oprations");
Console.WriteLine("Please Enter First Value :");
int value1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Please Enter Second Value :");
int value2 = Convert.ToInt32(Console.ReadLine());
int addition = value1 + value2;
int substract = value1 - value2;
int multiply = value1 * value2;
int divide = value1 / value2;
int modulus = value1 % value2;
Console.WriteLine("The Addition of Value is :" + addition);
Console.WriteLine("The Addition of Value is :" + substract);
Console.WriteLine("The Addition of Value is :" + multiply);
Console.WriteLine("The Addition of Value is :" + divide);
Console.WriteLine("The Addition of Value is :" + modulus);